### ISSUE TITLE
Module build failed 

### ISSUE THREAD

**Issue by santoshgistto** [Canner/canner-firebase-cms#16]
`npm start`

`RROR in ../canner.schema.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/name/react/canner-firebase-cms/canner.schema.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
P`

**Comment by chilijung** [comment]
This is fixed in `master` branch, please clone again and try thanks!
